on:
  push:
    branches:
      - main
jobs:
  BuildAPK:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: automated-build-android-app-with-github-action
        uses: amirisback/automated-build-android-app-with-github-action@2.2.3
            
  
